### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by Alfriadox** [rcos/Telescope#18]
Items marked with `(?)` are not concrete requirements or do not have established requirements for design and implementation. 

EDIT (Feb 9 2021): With the new back end, a lot of these requirements have changed and this roadmap is less accurate. You may still use this a rough guide, but it does not quite match the actual implementation requirements. 

## Specific Features
- [ ] User Settings (#16) 
  - [ ] Change settings form
  - [ ] Change password form
    - [ ] Poor password response
    - [ ] Incorrect current password response
    - [ ] New password and confirm new password do not match response
    - [ ] (Possible bug) Should changing password logout user everywhere else?
      - [ ] (Possible fix) change how user identity is stored in the session cookies / identity token.
    - [ ] Success response
    - [ ] Email Adding, Verification and Visibility
      - [ ] Form page (#47)
      - [ ] Send verification email
      - [ ] Create database record
      - [ ] Success response
      - [ ] Fail Response 
      - [ ] Remove Database record
      - [x] Database Janitor
  - [ ] Link accounts (#5)
    - [ ] GitHub
    - [ ] Discord
    - [ ] Mattermost (?)
    - [ ] RPI CAS
    - [ ] Link account process
      - [ ] Redirect to OAuth page
      - [ ] User does authentication
      - [ ] OAuth redirects back to telescope
      - [ ] Handle OAuth response
        - Perhaps use an OAuth library for this or something
        - [ ] Store auth token in database with user record via PostgREST API
        - [ ] Success response
        - [ ] Failure response
    - [ ] Unlink account proccess
      - [ ] Remove OAuth token from database
      - [ ] Success response
      - [ ] Failure response
  - [ ] Delete account (#15) 
    - [ ] Should be done in database transaction to avoid partial results.
    - [ ] Fail if sysadmin (The sysadmin account should not be removed)
    - [ ] Remove from groups
    - [ ] Orphan any projects as PM
    - [ ] remove all attendance records 
    - [ ] remove all emails
    - [ ] remove user record
    - [ ] success response
    - [ ] failure response
  - [ ] Active / Inactive state (?)
    - Feature/implementation still under consideration
- [ ] User pages / profiles (#11)
  - [x] Display name
  - [x] Display profile picture
  - [x] Display bio as rendered markdown
  - [x] Display emails
  - [ ] Display groups 
  - [ ] Display highest permission/role
    - [ ] mentor
    - [ ] coordinator
    - [ ] faculty
    - [ ] member (default)
  - [ ] display attendance to privileged users
  - [x] display 'user settings' button to privileged users
  - [ ] display linked accounts
  - [ ] display projects
    - [ ] Owned projects as PM
    - [ ] others as member
    - [ ] group by activity (?)
  - [ ] display user blog (?)
    - Should this be on a profile or different page?
    - Design under consideration
- [ ] Blog system (#7) (?)
  - Should this be a 1.0 feature or 1.1?
  - Feature may be scrapped entirely in favour of Submitty, Discord, and other communication media.
  - Feature still under consideration.
  - Design and requirements under consideration. Subject to change.
  - [ ] Personal / User / Developer blogs (could be used for status updates)
  - [ ] Project blogs (could be used for project proposals etc.)
  - [ ] Group blogs (could be used for communicating with small groups)
  - [ ] RCOS Achievements / Site blog
    - Could be implemented as special case statically generated blog.
  - [ ] Blog subscriptions (?)
    - Not 1.0.0.
    - [ ] Subscribe to blog.
    - [ ] Unsubscribe from blog.
    - [ ] Blog feed page.
  - [ ] Blog Comments (?)
    - Not 1.0.0
    - [ ] CRUD operations on comment on blog post
- [ ] Users / Developers page
  - [x] Display list of users
  - [ ] Pagination
  - [ ] Search feature
  - [ ] Toggle active/inactive (?)
- [ ] Projects page
  - [ ] Display list of projects
  - [ ] Pagination
  - [ ] Search feature
  - [ ] Toggle active/inactive
- [ ] Project Pages (#12)
  - [ ] Display PM
  - [ ] Display Members
  - [ ] Display link to repo
  - [ ] Display description as rendered markdown
  - [ ] For logged in users
    - [ ] Join/Leave button
  - [ ] For privileged users
    - [ ] Project settings button
    - [ ] Transfer ownership button
    - [ ] Toggle active/inactive
    - [ ] Delete project
  - [ ] Multiple PMs (?)
  - [ ] Display project blog (?)
- [ ] API and Playground (#13)
  - Not 1.0.0
  - Endpoints and implementation subject to change.
- [ ] Attendance system (#6)
  - [ ] Methods / Preferences
    - [ ] [offsite] Submitty phrase
      - [ ] allow users to display submitty phrase using telescope
    - [ ] [offsite] Venue QR Code
    - [ ] [offsite, legacy] Observatory code
    - [ ] Telescope Phrase
    - [ ] Telescope Link
      - [ ] Generate QR code (that redirects to link)
    - [ ] Randomly generated code (like observatory)
    - [ ] Manually verify attendance on a per person basis
    - [ ] Toggle randomly requiring verification. 
    - [ ] Set expiration time
      - [ ] default 1 hour (?)
        - subject to change
    - [ ] Live vs asynchronous attendance preferences (?) 
  - [ ] Privileged user creates attendance event on group. 
    - [ ] Specify methods acceptable
  - [ ] Member checks in using one of the available methods
   - [ ] Manual verification required response
   - [ ] Success response
   - [ ] Failure response
- [ ] Groups system (#8)
  - [ ] Privileged user CRUD operations on groups
- [ ] Calendar (#17)
  - [ ] Link the google spreadsheet.
  - [ ] Native calendar
    - Not 1.0.0
    - Design and implementation under consideration. Subject to change.
    - [ ] Calendar page
    - [ ] CRUD operations on the calendar
    - [ ] Possible automatic integration with attendance system.
- [ ] On site diagnostics and server log for sysadmin (?)
  - Not 1.0.0.
- [ ] Submissions system for gradeables (like status updates) (?)
  - Not 1.0.0.
## More general goals/considerations
- Page responsiveness/interactivity
  - Currently everything is verified and rendered server side. This has worked so far but may present issues long term. Currently we are not using any frontend frameworks beyond handlebars (for templating) and bootstrap (for styling). It will likely be useful to add a framework or put in a significant amount of work at some point for client side rendering and interactivity. 
  - It would take more effort, but might be useful at some point, especially depending on the eventual scale of this project to separate the frontend and backend further. 
- Change how sessions are handled so that changing a password invalidates other user sessions. 
- Add testing of some kind to help maintain the codebase.

**Comment by Alfriadox** [comment]
With the major rework of the back-end complete, this roadmap is now inaccurate.
